
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakshi
 */
public class AddCourse extends javax.swing.JFrame {

    JFileChooser jf_wp;
    JFileChooser jf_sp;
    JFileChooser jf_sv;

    /**
     * Creates new form AddCourse
     */
    public AddCourse() {
        initComponents();
        setVisible(true);
        setSize(800, 800);
        jf_wp = new JFileChooser();
        jf_sp = new JFileChooser();
        jf_sv = new JFileChooser();
        jc_category.addItem("App Development");
        jc_category.addItem("Software Development");
        jc_category.addItem("Web Development");
        jc_category.removeAllItems();
        for(int i=0;i<GlobalData.category.length;i++)
        {
            jc_category.addItem(GlobalData.category[i]);
                    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        tf_square = new javax.swing.JTextField();
        tf_wide = new javax.swing.JTextField();
        tf_pre = new javax.swing.JTextField();
        tf_amount = new javax.swing.JTextField();
        tf_samplevideo = new javax.swing.JTextField();
        bt_sv = new javax.swing.JButton();
        bt_wp = new javax.swing.JButton();
        bt_sp = new javax.swing.JButton();
        jc_category = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 120, 20);

        jLabel2.setText("Enter Description");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 120, 20);

        jLabel3.setText("Select Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 100, 20);

        jLabel4.setText("Select Wide Photo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 120, 20);

        jLabel5.setText("Select Square Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 140, 20);

        jLabel6.setText("Enter Pre-Requisite");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 130, 30);

        jLabel7.setText("Enter Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 250, 130, 16);

        jLabel8.setText("Select Sample Video");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 140, 20);
        getContentPane().add(tf_name);
        tf_name.setBounds(180, 10, 150, 30);

        ta_description.setColumns(20);
        ta_description.setRows(5);
        jScrollPane1.setViewportView(ta_description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 40, 220, 50);
        getContentPane().add(tf_square);
        tf_square.setBounds(160, 170, 130, 26);

        tf_wide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_wideActionPerformed(evt);
            }
        });
        getContentPane().add(tf_wide);
        tf_wide.setBounds(160, 130, 140, 26);
        getContentPane().add(tf_pre);
        tf_pre.setBounds(190, 200, 100, 26);
        getContentPane().add(tf_amount);
        tf_amount.setBounds(190, 240, 100, 26);
        getContentPane().add(tf_samplevideo);
        tf_samplevideo.setBounds(170, 290, 120, 26);

        bt_sv.setText("Browse");
        bt_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_svActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sv);
        bt_sv.setBounds(310, 290, 90, 30);

        bt_wp.setText("Browse");
        bt_wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_wpActionPerformed(evt);
            }
        });
        getContentPane().add(bt_wp);
        bt_wp.setBounds(300, 130, 88, 29);

        bt_sp.setText("Browse");
        bt_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_spActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sp);
        bt_sp.setBounds(300, 170, 88, 29);

        jc_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jc_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_categoryActionPerformed(evt);
            }
        });
        getContentPane().add(jc_category);
        jc_category.setBounds(190, 100, 160, 27);

        jButton4.setText("ADD COURSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(140, 330, 140, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_wpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_wpActionPerformed
        int r = jf_wp.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            File f = jf_wp.getSelectedFile();
            String path1 = f.getPath();
            tf_wide.setText(path1);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_wpActionPerformed

    private void jc_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_categoryActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jc_categoryActionPerformed

    private void bt_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_spActionPerformed
        int y = jf_sp.showOpenDialog(this);
        if (y == JFileChooser.APPROVE_OPTION) {
            File f = jf_sp.getSelectedFile();
            String path1 = f.getPath();
            tf_square.setText(path1);

        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_spActionPerformed

    private void bt_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_svActionPerformed
        int r = jf_sv.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            File f = jf_sv.getSelectedFile();
            String path1 = f.getPath();
            tf_samplevideo.setText(path1);

        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_svActionPerformed

    private void tf_wideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_wideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_wideActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Thread(new job()).start();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    class job implements Runnable {

        @Override
        public void run() {

            try {

                String name = tf_name.getText();
                String description = ta_description.getText();
               String amount = (tf_amount.getText());
                String pre = tf_pre.getText();

                String category = jc_category.getSelectedItem().toString();

                HttpResponse<String> httpresponse = Unirest.post("http://"+GlobalData.host+"/AddCourse")
                        .queryString("name", name)
                        .queryString("description", description)
                        .queryString("category", category)
                        .queryString("pre", pre)
                        .queryString("amount", amount)
                        .field("widephoto", new File(tf_wide.getText()))
                        .field("squarephoto", new File(tf_square.getText()))
                        .field("samplevideo", new File(tf_samplevideo.getText()))
                        .asString();
                if(httpresponse.getBody().equals("fail"))
                    JOptionPane.showMessageDialog(rootPane, "failure");
                else
                    JOptionPane.showMessageDialog(rootPane, "you added successfully");
                    
                

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sp;
    private javax.swing.JButton bt_sv;
    private javax.swing.JButton bt_wp;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jc_category;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_pre;
    private javax.swing.JTextField tf_samplevideo;
    private javax.swing.JTextField tf_square;
    private javax.swing.JTextField tf_wide;
    // End of variables declaration//GEN-END:variables
}
