
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakshi
 */
public class AdminHome extends javax.swing.JFrame {
  

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        
        initComponents();
        setVisible(true);
        setSize(800,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_addcourse = new javax.swing.JButton();
        bt_view = new javax.swing.JButton();
        bt_managevideos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bt_addcourse.setText("Add Course");
        bt_addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addcourseActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addcourse);
        bt_addcourse.setBounds(50, 20, 140, 70);

        bt_view.setText("View All Courses");
        bt_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_viewActionPerformed(evt);
            }
        });
        getContentPane().add(bt_view);
        bt_view.setBounds(50, 100, 140, 60);

        bt_managevideos.setText("Manage Videos");
        bt_managevideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_managevideosActionPerformed(evt);
            }
        });
        getContentPane().add(bt_managevideos);
        bt_managevideos.setBounds(50, 180, 140, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addcourseActionPerformed
  AddCourse obj=new AddCourse();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addcourseActionPerformed

    private void bt_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_viewActionPerformed
Viewcourses obj=new Viewcourses();





        // TODO add your handling code here:
    }//GEN-LAST:event_bt_viewActionPerformed

    private void bt_managevideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_managevideosActionPerformed
Managevideos obj=new Managevideos();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_managevideosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addcourse;
    private javax.swing.JButton bt_managevideos;
    private javax.swing.JButton bt_view;
    // End of variables declaration//GEN-END:variables
}
