
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakshi
 */
public class ChangePass extends javax.swing.JFrame {
String email;
    /**
     * Creates new form ChangePass
     */
    public ChangePass(String email) {
        initComponents();
        setSize(400,400);
        this.email=email;
        lb1.setText("Your Email:"+email);
        Color cl=new Color(204,215,116);
        getContentPane().setBackground(cl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_oldpass = new javax.swing.JPasswordField();
        tf_newpass = new javax.swing.JPasswordField();
        tf_confirmpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        lb1.setText("Your Email");
        getContentPane().add(lb1);
        lb1.setBounds(20, 30, 290, 40);

        jLabel2.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        jLabel2.setText("Enter Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 170, 20);

        jLabel3.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 120, 24);

        jLabel4.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 190, 160, 24);

        jButton1.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 240, 100, 40);
        getContentPane().add(tf_oldpass);
        tf_oldpass.setBounds(180, 90, 210, 26);
        getContentPane().add(tf_newpass);
        tf_newpass.setBounds(180, 150, 220, 26);

        tf_confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_confirmpassActionPerformed(evt);
            }
        });
        getContentPane().add(tf_confirmpass);
        tf_confirmpass.setBounds(180, 190, 220, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(tf_oldpass.getText()==""||tf_newpass.getText()==""||tf_confirmpass.getText()=="")
          JOptionPane.showMessageDialog(rootPane,"All Fields must be filled");
      else if(!(tf_confirmpass.getText().equals(tf_newpass.getText())))
          JOptionPane.showMessageDialog(rootPane,"Confirm field and new password field must match!");
      else
      {
          new Thread(new job_changepass()).start();
          
          
      }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_confirmpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb1;
    private javax.swing.JPasswordField tf_confirmpass;
    private javax.swing.JPasswordField tf_newpass;
    private javax.swing.JPasswordField tf_oldpass;
    // End of variables declaration//GEN-END:variables
class job_changepass implements Runnable
{

        @Override
        public void run() {
          HttpResponse res;
            try {
                res = Unirest.get("http://"+GlobalData.host+"/changepass").queryString("email",email).queryString("old pass",tf_oldpass.getText()).queryString("new pass",tf_newpass.getText()).asString();
            
          if(res.getBody().equals("success"))
              JOptionPane.showMessageDialog(rootPane,"Password Changed Successfully");
          else
              JOptionPane.showMessageDialog(rootPane,"Fail");
        }
          catch (UnirestException ex) {
                Logger.getLogger(ChangePass.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
    
}
}
