
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakshi
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setSize(400, 400);
        lb_enterotp.setVisible(false);
        lb_heading.setVisible(false);
        tf_otp.setVisible(false);
        bt_next.setVisible(false);
        lb_last.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        bt_continue = new javax.swing.JButton();
        lb_heading = new javax.swing.JLabel();
        lb_enterotp = new javax.swing.JLabel();
        tf_otp = new javax.swing.JTextField();
        bt_next = new javax.swing.JButton();
        lb_last = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        jLabel1.setText("Enter Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 40);

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        getContentPane().add(tf_email);
        tf_email.setBounds(110, 20, 220, 30);

        bt_continue.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        bt_continue.setText("Continue");
        bt_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_continueActionPerformed(evt);
            }
        });
        getContentPane().add(bt_continue);
        bt_continue.setBounds(110, 70, 110, 40);

        lb_heading.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        lb_heading.setText("An Otp is sent to you on ");
        getContentPane().add(lb_heading);
        lb_heading.setBounds(0, 120, 400, 40);

        lb_enterotp.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        lb_enterotp.setText("Enter Otp:");
        getContentPane().add(lb_enterotp);
        lb_enterotp.setBounds(20, 160, 120, 30);

        tf_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_otpActionPerformed(evt);
            }
        });
        getContentPane().add(tf_otp);
        tf_otp.setBounds(100, 160, 100, 26);

        bt_next.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        bt_next.setText("Next");
        bt_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nextActionPerformed(evt);
            }
        });
        getContentPane().add(bt_next);
        bt_next.setBounds(90, 200, 97, 32);

        lb_last.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 0, 24)); // NOI18N
        lb_last.setText("Your Current Password Is:");
        getContentPane().add(lb_last);
        lb_last.setBounds(10, 256, 350, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_continueActionPerformed
        // TODO add your handling code here:
        bt_continue.setEnabled(false);
        new Thread(new job_forget()).start();


    }//GEN-LAST:event_bt_continueActionPerformed

    private void bt_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_nextActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_otpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_otpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_continue;
    private javax.swing.JButton bt_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_enterotp;
    private javax.swing.JLabel lb_heading;
    private javax.swing.JLabel lb_last;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_otp;
    // End of variables declaration//GEN-END:variables
  class job_forget implements Runnable {

        String newn;

        @Override
        public void run() {
            HttpResponse res;
            try {
                res = Unirest.get("http://"+GlobalData.host+"/forgotpassword").queryString("email", tf_email.getText()).asString();
                
                StringTokenizer st = new StringTokenizer(res.getBody().toString(), ";");

                String contact = st.nextToken();
                String pass = st.nextToken();
                lb_heading.setVisible(true);
                newn = "*******"+contact.substring(7);
                lb_heading.setText("An Otp is sent on:"+newn);
                lb_enterotp.setVisible(true);
                tf_otp.setVisible(true);
                bt_next.setVisible(true);
                int otp = (int) (1000 + 8999 * Math.random());
                sms_sender.send(contact, "Hello "+tf_email.getText()+"!"+"\nYour Otp Is:"+otp);

                bt_next.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (tf_otp.getText().equals(otp+"")) {
                            lb_last.setVisible(true);
                            lb_last.setText("Your password is:" + pass);
                        }

                    }
                });

            } catch (UnirestException ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
 


}
