
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakshi
 */
public class Managevideos extends javax.swing.JFrame {

    JFileChooser jf;
    mytablemodel tm;
    ArrayList<videos> al;

    /**
     * Creates new form Managevideos
     */
    public Managevideos() {
        initComponents();
        setSize(800, 800);
        setVisible(true);
        cb1_category.removeAllItems();

        for (int i = 0; i < GlobalData.category.length; i++) {
            cb1_category.addItem(GlobalData.category[i]);
            jf = new JFileChooser();
            al = new ArrayList<>();
            tm = new mytablemodel();
            jt2.setModel(tm);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb1_category = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        bt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setText("Select Category");
        getContentPane().add(lb1);
        lb1.setBounds(190, 30, 110, 40);

        jLabel1.setText("Select Course");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 70, 100, 20);

        cb1_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb1_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1_categoryActionPerformed(evt);
            }
        });
        getContentPane().add(cb1_category);
        cb1_category.setBounds(310, 30, 200, 27);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(310, 60, 200, 30);

        jLabel2.setText("Enter Lecture No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 110, 30);
        getContentPane().add(tf1);
        tf1.setBounds(130, 110, 100, 26);

        jLabel3.setText("Enter Title");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 100, 30);

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(130, 140, 100, 26);

        jLabel4.setText("Enter Duration");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 180, 120, 20);
        getContentPane().add(tf3);
        tf3.setBounds(130, 170, 100, 26);

        jLabel5.setText("Select Video");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 100, 20);
        getContentPane().add(tf4);
        tf4.setBounds(130, 210, 100, 26);

        bt1.setText("BROWSE");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(230, 210, 90, 30);

        jLabel6.setText("Select Thumbnail");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 150, 16);
        getContentPane().add(tf5);
        tf5.setBounds(130, 250, 100, 26);

        bt2.setText("BROWSE");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(230, 250, 94, 29);

        bt3.setText("ADD");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(140, 290, 75, 29);

        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 120, 320, 240);

        bt_delete.setText("Delete Video");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(bt_delete);
        bt_delete.setBounds(420, 380, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1_categoryActionPerformed
        new Thread(new job_()).start();

    }//GEN-LAST:event_cb1_categoryActionPerformed
    class job_ implements Runnable {

        @Override
        public void run() {
            if (cb1_category.getSelectedItem() != null) {
                String selection = cb1_category.getSelectedItem().toString();
                try {
                    HttpResponse res = Unirest.get("http://"+GlobalData.host+"/getcourse").queryString("selection", selection).asString();
                    StringTokenizer st = new StringTokenizer(res.getBody().toString(), ";");

                    cb2.removeAllItems();
                    while (st.hasMoreTokens()) {
                        cb2.addItem(st.nextToken());

                    }

                    // TODO add your handling code here:
                } catch (UnirestException ex) {
                    ex.printStackTrace();
                }
            }

        }

    }


    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        int r = jf.showOpenDialog(this);
        if (r == jf.APPROVE_OPTION) {
            File f = jf.getSelectedFile();
            String s = f.getPath();
            tf4.setText(s);

        }

// TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        int r = jf.showOpenDialog(this);
        if (r == jf.APPROVE_OPTION) {
            File f = jf.getSelectedFile();
            String s = f.getPath();
            tf5.setText(s);

        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed

        new Thread(new job_add()).start();

    }//GEN-LAST:event_bt3ActionPerformed

    class job_add implements Runnable {

        @Override
        public void run() {
            try {
                HttpResponse res = Unirest.post("http://"+GlobalData.host+"/addvideos")
                        .queryString("LectureNo", tf1.getText())
                        .queryString("Duration", tf3.getText())
                        .queryString("Title", tf2.getText())
                        .queryString("CourseName", cb2.getSelectedItem())
                        .field("VideoPath", new File(tf4.getText()))
                        .field("VideoThumbnail", new File(tf5.getText()))
                        .asString();
                if (res.getBody().equals("success")) {
                    JOptionPane.showMessageDialog(rootPane, "you added successfully");

                    new Thread(new job()).start();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failure");

                }
            } catch (UnirestException ex) {
                Logger.getLogger(Managevideos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }


    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
        new Thread(new job()).start();

    }//GEN-LAST:event_cb2ItemStateChanged

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed

        new Thread(new job_delete()).start();
// TODO add your handling code here:
    }//GEN-LAST:event_bt_deleteActionPerformed

    class job_delete implements Runnable {

        @Override
        public void run() {

            int r = jt2.getSelectedRow();
            if (r == -1) {
                JOptionPane.showMessageDialog(rootPane, "Please Select Something");
            } else {
                int k = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete?");
                if (k == JOptionPane.YES_OPTION) {
                    try {
                        int videoid = al.get(r).VideoId;
                        HttpResponse res = Unirest.get("http://"+GlobalData.host+"/deletevideo").queryString("videoid", videoid + "").asString();
                        if (res.getBody().equals("success")) {
                            new Thread(new Managevideos.job()).start();

                        } else {

                            JOptionPane.showMessageDialog(rootPane, "Failed");

                        }

                    } catch (UnirestException ex) {
                        ex.printStackTrace();
                    }

                } else {

                }

            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managevideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managevideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managevideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managevideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managevideos().setVisible(true);
            }
        });
    }

    class mytablemodel extends AbstractTableModel {

        String names[] = {"VideoId", "LectureNo", "Title", "Duration"};

        public String getColumnName(int column) {
            return names[column];

        }

        @Override
        public int getRowCount() {
            return al.size();

        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int row, int col) {
            videos c = al.get(row);
            if (col == 0) {
                return c.VideoId;
            } else if (col == 1) {
                return c.Lectureno;
            } else if (col == 2) {
                return c.Title;
            } else {
                return c.Duration;
            }

        }

    }

    class job implements Runnable {

        @Override
        public void run() {
            try {
                HttpResponse<String> httpresponse;

                httpresponse = Unirest.get("http://"+GlobalData.host+"/fetchvideos").queryString("Course", cb2.getSelectedItem()).asString();

                StringTokenizer st = new StringTokenizer(httpresponse.getBody(), "~");

                al.clear();
                while (st.hasMoreTokens()) {
                    String video = st.nextToken();
                    StringTokenizer st2 = new StringTokenizer(video, ";");
                    int videoid = Integer.parseInt(st2.nextToken());
                    int lecture = Integer.parseInt(st2.nextToken());
                    String title = st2.nextToken();
                    int duration = Integer.parseInt(st2.nextToken());
                    al.add(new videos(videoid, lecture, duration, title));
                }
                tm.fireTableDataChanged();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt_delete;
    private javax.swing.JComboBox<String> cb1_category;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt2;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
