
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sakshi
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setSize(500, 500);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_phone = new javax.swing.JTextField();
        tf_photo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_signup = new javax.swing.JButton();
        tf_cpassword = new javax.swing.JPasswordField();
        bt_photo = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 80, 16);
        getContentPane().add(tf_email);
        tf_email.setBounds(190, 20, 150, 26);
        getContentPane().add(tf_name);
        tf_name.setBounds(190, 60, 140, 26);
        getContentPane().add(tf_phone);
        tf_phone.setBounds(190, 180, 130, 26);
        getContentPane().add(tf_photo);
        tf_photo.setBounds(190, 220, 80, 26);

        jLabel2.setText("Enter Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 90, 16);

        jLabel3.setText("Enter Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 20);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 120, 20);

        jLabel5.setText("Enter Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 100, 30);

        jLabel6.setText("Select Photo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(35, 220, 90, 16);

        bt_signup.setText("Sign Up");
        bt_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signupActionPerformed(evt);
            }
        });
        getContentPane().add(bt_signup);
        bt_signup.setBounds(120, 260, 92, 29);
        getContentPane().add(tf_cpassword);
        tf_cpassword.setBounds(190, 140, 140, 26);

        bt_photo.setText("Browse");
        bt_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_photoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_photo);
        bt_photo.setBounds(280, 220, 80, 29);
        getContentPane().add(tf_password);
        tf_password.setBounds(190, 110, 130, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signupActionPerformed
        if (tf_email.getText().equals("") || tf_name.getText().equals("") || tf_phone.getText().equals("") || tf_photo.getText().equals("") || tf_cpassword.getText().equals("") || tf_password.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Fill Everything");
        } else if (!tf_cpassword.getText().equals(tf_password.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Your passwords dont match");
        } else {
            new Thread(new job_signup()).start();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_signupActionPerformed
    File f;
    private void bt_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_photoActionPerformed
        JFileChooser jf = new JFileChooser();
        int r = jf.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            f = jf.getSelectedFile();
        }
        tf_photo.setText(f.getPath());

// TODO add your handling code here:
    }//GEN-LAST:event_bt_photoActionPerformed
    class job_signup implements Runnable {

        @Override
        public void run() {

            try {
                HttpResponse res = Unirest.post("http://" + GlobalData.host + "/signup").queryString("email", tf_email.getText())
                        .queryString("password", tf_password.getText())
                        .queryString("phone", tf_phone.getText())
                        .queryString("name", tf_name.getText())
                        .field("profilephoto", new File(tf_photo.getText()))
                        .asString();
                if (res.getBody().equals("success")) {
                    JOptionPane.showMessageDialog(rootPane, "success");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "fail");
                }

            } catch (Exception e) {
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_photo;
    private javax.swing.JButton bt_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField tf_cpassword;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_photo;
    // End of variables declaration//GEN-END:variables
}
