/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakshi
 */
public class SingleCategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SingleCategoryPanel
     */
    public SingleCategoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        lb1.setFont(new java.awt.Font("Krinkes Regular PERSONAL USE", 3, 36)); // NOI18N
        lb1.setText("Courses Under ");
        add(lb1);
        lb1.setBounds(10, 10, 530, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    // End of variables declaration//GEN-END:variables
}
